# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Priyanka Das Rajkakati
description:         'PriyanKaleidoscope'
url:                 http://lanyon.getpoole.com
tagline:             Aerospace Engineer | Artist
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Priyanka Das Rajkakati
  url:               https://PriyankaRajkakati.Space
  email:             contact@PriyankaRajkakati.Space

# Custom vars
version:             1.0.0
